### ISSUE TITLE
ignored tags not working

### ISSUE THREAD

**Issue by p-hueber** [JakeWharton/qbt-orphaned-downloads#12]
For some reason, my list of ignored tags is ignored.

I set the `QBT_IGNORE_TAGS` environment variable to `TV` in my `docker-compose.yaml`:
```
qbt-orphaned-downloads:
  container_name: qbt-orphaned-downloads
  image: jakewharton/qbt-orphaned-downloads:1
  restart: unless-stopped
  volumes:
    - /Downloads/Movies:/downloads
  environment:
    - "QBT_HOST=http://qbittorrent:8088"
    - "QBT_IGNORE_TAGS=TV"
    - "DEBUG=true"
    - "CRON=0 * * * *"
  depends_on: [qbittorrent]

```

But this is ignored entirely and all my TV-tagged torrents end up with an additional "Orphaned" tag.

Here's one example from the debug log:
```
--- Monarch.Legacy.of.Monsters.S01E10.Beyond.Logic.1080p.ATVP.WEB-DL.DDP5.1.H.264-NTb.mkv ---
Tags: TV
State: TorrentStates.FORCED_UPLOAD
Monarch.Legacy.of.Monsters.S01E10.Beyond.Logic.1080p.ATVP.WEB-DL.DDP5.1.H.264-NTb.mkv Ignored (stats missing)
Orphaned? True
Tagging Monarch.Legacy.of.Monsters.S01E10.Beyond.Logic.1080p.ATVP.WEB-DL.DDP5.1.H.264-NTb.mkv

```

The "stats missing" error is expected and the very reason I want to ignore this torrent.

**Comment by JakeWharton** [comment]
Weird. I will try to take a look at some point, but I can't promise it'll be super soon.

**Comment by JakeWharton** [comment]
Also: I don't use this feature. That's probably why it's broken!

**Comment by JakeWharton** [comment]
![Screenshot 2024-12-27 at 2 16 17 PM](https://github.com/user-attachments/assets/725993ad-b776-41c7-8181-9da4c06bee0b)

I just tested this and it worked for me.

This is using the new #13 feature which refactored a lot of the logic. There is still a single-tag mode which has the old behavior, and there are tests now which validate that a matching ignored tag ensures no tags are added.

I'll release a new tagged version soon. Let me know if the problem is not fixed when that one comes out and you have a chance to upgrade.
